# -*- coding: utf-8 -*-
"""FinalCode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2qWpgRxE3udt_T_GKDDv-qywBZifdKD

# Importing & Cleansing Data
"""

import os
import warnings
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.feature_selection import RFE
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model, ensemble, tree
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.model_selection import cross_val_score,GridSearchCV,cross_validate
from sklearn.metrics import confusion_matrix, auc,roc_auc_score,roc_curve,recall_score,classification_report
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 100, 'display.max_columns', 400)

# Commented out IPython magic to ensure Python compatibility.
## Load Datasets

# load dataset
from google.colab import drive
drive.mount("/content/drive/")
# %cd '/content/drive/MyDrive'
!pwd #Prints the present working directory
oulad_assessment = pd.read_csv('assessments.csv')
oulad_courses = pd.read_csv('courses.csv')
oulad_student_assessment = pd.read_csv('studentAssessment.csv')
oulad_student_info = pd.read_csv('studentInfo.csv')
oulad_student_registration = pd.read_csv('studentRegistration.csv')
oulad_student_vle = pd.read_csv('studentVle.csv')
oulad_vle = pd.read_csv('vle.csv')

## Assessments
oulad_assessment['date'] = oulad_assessment['date'].fillna(int(oulad_assessment['date'].astype(float).mean()))
#print(oulad_assessment['code_module'].unique())
#print(oulad_assessment['assessment_type'].unique())
#plt.hist(oulad_assessment['date'].astype(int), bins=7)
#plt.show()

## Student Assessment
oulad_student_assessment = oulad_student_assessment.dropna()
#oulad_student_assessment.head()

## Student Registration
oulad_student_registration['date_unregistration'] = ['0' if pd.isnull(days) else '1' for days in oulad_student_registration['date_unregistration']]
oulad_student_registration['date_registration']   = oulad_student_registration['date_registration'].fillna(0).astype(float).apply(abs)
#oulad_student_registration.head()

## Student Info
#print(oulad_student_info['imd_band'].unique())

oulad_student_info['imd_band'] = oulad_student_info['imd_band'].fillna(oulad_student_info['imd_band'].mode()[0])
#oulad_student_info.head()

# VLE
oulad_vle = oulad_vle.drop(['week_from', 'week_to'], axis = 1)
#oulad_vle.head()

"""# Merging Data & Exploratory Data Analysis

Student VLE & VLE
"""

# Merge Student VLE & VLE
student_vle_merge_vle = oulad_student_vle.merge(oulad_vle,
                                                on=['id_site', 'code_module', 'code_presentation'],
                                                how = 'left')

student_vle_merge_vle[(student_vle_merge_vle['id_student']==28400) & (student_vle_merge_vle['date']<0)].head(10)

student_vle_merge_vle['Click_Timing'] = ['Before' if date < 0 else 'After' for date in student_vle_merge_vle['date']]

# Creating After clicks and Before Clicks columns based on the data

student_vle_merge_vle['After_Clicks'] = np.where(student_vle_merge_vle['Click_Timing'] =='After',
                                                 student_vle_merge_vle['sum_click'], 0)

student_vle_merge_vle['Before_Clicks']= np.where(student_vle_merge_vle['Click_Timing'] =='Before',
                                                 student_vle_merge_vle['sum_click'], 0)

# Create a new dataframe by Grouping the columns
student_vle_merge_vle_group = student_vle_merge_vle.groupby(['code_module',
                                                             'code_presentation',
                                                             'id_student']
                                                            ,as_index=False)[['sum_click', 'After_Clicks', 'Before_Clicks']].sum()

#student_vle_merge_vle_group.isnull().sum()

"""Student Registration & Courses"""

student_registration_merge_courses = oulad_student_registration.merge(oulad_courses,
                                                                      on = ['code_module', 'code_presentation'],
                                                                      how = 'left')

student_registration_merge_courses['Year'] = student_registration_merge_courses['code_presentation'].str[0:4]
student_registration_merge_courses['Starting_Month'] = ['February' if code[-1] == 'B' else 'October'
                                                        for code in student_registration_merge_courses['code_presentation']]

# From the below table we can see that course length doesn't have much difference for the student who withdrawn and students who completed the course

student_registration_merge_courses.groupby('date_unregistration', as_index=False)['module_presentation_length'].mean()

"""Assessments & Student Assessments"""

student_assessment_merge_assessment = oulad_student_assessment.merge(oulad_assessment,
                                                                     on = ['id_assessment'], how='left' )
#student_assessment_merge_assessment.dtypes

# There would have been instances where students submitted their assignments later than the deadline. In this step,
# using the date_submitted (days after student recieved their assignment) column and date (deadline in days for the assignment)
# we can check whether their was a late submission or not (0 : Late, 1:OnTime)

student_assessment_merge_assessment['Late_submission'] = ['0' if int(student_assessment_merge_assessment['date_submitted'].iloc[i])
                                                          > int(student_assessment_merge_assessment['date'].iloc[i]) else '1'
                                                         for i in range(len(student_assessment_merge_assessment))]

print('Percentage of Late Submissions From Students are : ')
print((len(student_assessment_merge_assessment[student_assessment_merge_assessment['Late_submission']=='0'])/len(student_assessment_merge_assessment)*100))
print('We can see that approximately 30 percent of students submitted their assigments late')

# Function to plot stacked plot
# Paramteres :-
# data :- Dataframe used for plotting
# column_one :- Column One to group by
# column_two : Column Two to group by
# agg_column : Column to count numbers

def stacked_plot(data, column_one, column_two, agg_column, plot_size=(10, 5)):
    pal     = sns.color_palette("colorblind")
    grouped = data.groupby([column_one, column_two])[agg_column].count()
    grouped = grouped.groupby(level=0).apply(lambda x:100 * x / float(x.sum()))
    grouped = grouped.unstack(column_two).fillna(0)
    print(grouped)
    unique_list = list(data[column_two].unique())
    grouped[unique_list].plot(kind='bar', stacked=True, color=pal, figsize=plot_size)

## Creating a column for Social Science and STEM field

student_assessment_merge_assessment['Code_Category'] = ['Social_Science' if student_assessment_merge_assessment['code_module'].iloc[i] in ['AAA', 'BBB', 'GGG']
                                                        else 'STEM' for i in range(len(student_assessment_merge_assessment))]

# Social Science has more percentage of late submissions as compared to STEM
#stacked_plot(student_assessment_merge_assessment, 'Code_Category', 'Late_submission', 'id_student', plot_size=(8, 7))

# As from the description of table we know that score less than 40 is considered as Fail and above that is pass


student_assessment_merge_assessment['Result'] = ['Fail' if int(student_assessment_merge_assessment['score'].iloc[i]) < 40
                                                        else 'Pass' for i in range(len(student_assessment_merge_assessment))]

## Weightage of Assignment can have impact on the submissions and Result of students. I categorized the weight into

print(student_assessment_merge_assessment['weight'].unique())

percentage_segment = []

for percent in student_assessment_merge_assessment['weight']:
    if percent <= 10:
        percentage_segment.append('Low_Weightage')
    elif percent > 10 and percent <= 30:
        percentage_segment.append('Medium_Weightage')
    else:
        percentage_segment.append('High_Weightage')

student_assessment_merge_assessment['Weigthage'] = percentage_segment

# Following Plot shows the ratio of Pass and Fail in Late_submission.
# We can clearly see that Late Submissions have more Failure Rate as compared to people who submit on time.

#stacked_plot(student_assessment_merge_assessment, 'Late_submission', 'Result', 'id_student', plot_size=(8, 6))

student_assessment_merge_assessment.head()

"""VLE & Student Info"""

student_info = oulad_student_info.merge(student_vle_merge_vle_group,
                                        on = ['code_module', 'code_presentation', 'id_student'],
                                        how = 'left')

student_info['sum_click']     = student_info['sum_click'].fillna(student_info['sum_click'].mean())
student_info['After_Clicks']  = student_info['After_Clicks'].fillna(student_info['After_Clicks'].mean())
student_info['Before_Clicks'] = student_info['Before_Clicks'].fillna(student_info['Before_Clicks'].mean())

plt.figure(figsize = (10, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['final_result'])['After_Clicks'].mean().sort_values(ascending = False).plot(kind='bar')

## Even from the clicks data before the course even started, we can see that more the clicks more are the chances for student to pass.

plt.figure(figsize = (10, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['final_result'])['Before_Clicks'].mean().sort_values(ascending = False).plot(kind='bar')

## People with less credits have more chances to pass with distinction or pass because they have to study less
## People who withdrew has more average credits as compared to another.

plt.figure(figsize = (10, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['final_result'])['studied_credits'].mean().sort_values(ascending = False).plot(kind='bar')

plt.figure(figsize = (10, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['age_band'])['Before_Clicks'].mean().sort_values(ascending = False).plot(kind='bar')

plt.figure(figsize = (10, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['imd_band'])['sum_click'].sum().sort_values(ascending = False).plot(kind='bar')

plt.figure(figsize = (8, 5))
plt.xticks(rotation=90, fontsize=15)
plt.yticks(rotation=0, fontsize=12)
sns.set_style("whitegrid")
student_info.groupby(['gender'])['sum_click'].sum().sort_values(ascending = False).plot(kind='bar')

## Following plot shows us the number of students in each result category. Most of the data is in age band 0-55.
## There are very few data points for age >= 55.
## We can see that Failure and Withdrawn rate is greater in age_band 0-35

print(student_info.groupby(['age_band', 'final_result'])['id_student'].count().sort_values(ascending = False))
stacked_plot(student_info, 'age_band', 'final_result', 'id_student', plot_size=(10, 8))

# We can see from the plot that Failure Rate and Withdrawal Rate is high in people who have NO FORMAL EDUCATION and who have LOWER THAN A LEVEL EDUCATION
# Failure Rate is lowest in people who has Post Graduation.


#stacked_plot(student_info, 'highest_education', 'final_result', 'id_student', plot_size=(10, 8))

student_info['highest_education'].unique()

## Manioulating the feature higher_education

student_info['highest_education'] = [0 if education in ['A Level or Equivalent', 'Lower Than A Level', 'No Formal quals']
                                    else 1 for education in student_info['highest_education']]

## We can see from the plot that students with lower education has higher failure rate than the ones who had higher education

#stacked_plot(student_info, 'highest_education', 'final_result', 'id_student', plot_size=(10, 8))

## We can see that Failure Rate and Withdrawal rate is similar in all the regions.

#stacked_plot(student_info, 'region', 'final_result', 'id_student', plot_size=(15, 8))

#stacked_plot(student_info, 'imd_band', 'final_result', 'id_student', plot_size=(15, 8))

# We can see that Males are more in number as compared to females
sns.countplot(x ='gender', data = student_info)

plt.show()

## We can see that there is no difference between the Withdrawal Rates and Failure Rates for both the gender.

#stacked_plot(student_info, 'gender', 'final_result', 'id_student', plot_size=(10, 8))

# Following plot shows us the results by disability.  Withdrawn Rate is more in People who are disable.


#stacked_plot(student_info, 'disability', 'final_result', 'id_student', plot_size=(15, 8))

"""Student Info & Student Registration"""

student_registration_merge_courses = student_registration_merge_courses.drop('date_unregistration', axis = 1)

student_info = student_info.merge(student_registration_merge_courses,
                                 on = ['code_module', 'code_presentation', 'id_student'],
                                 how = 'left')

## Following Plot shows us the Result by Session. Failure Rate is more in people who took the course in February.
## Also withdrawn rate is slightly more in course starting in February.

#stacked_plot(student_info, 'Starting_Month', 'final_result', 'id_student', plot_size=(15, 8))

## There are less people who registered in February as compared to October. But still the failure and withdrawn rate
## is more for february. May be the students don't like content or the course in February.
sns.countplot(x ='Starting_Month', data = student_info)

# Show the plot
#plt.show()

## We can clearly see from the plot that we have the least failure and withdrawn rate in the students who did not
## took the course before or number of previous attempts are zero.

#stacked_plot(student_info, 'num_of_prev_attempts', 'final_result', 'id_student', plot_size=(15, 8))

student_info['num_of_prev_attempts'] = [0 if attempts == 0 else 1 for attempts in student_info['num_of_prev_attempts']]

## Still there is imbalance in the feature but it's better than the initial.
sns.countplot(x ='num_of_prev_attempts', data = student_info)

#plt.show()

# We can clearly see that people with previous attempts have more failure and withdrawn rate.

#stacked_plot(student_info, 'num_of_prev_attempts', 'final_result', 'id_student', plot_size=(15, 8))

## We can see that

#stacked_plot(student_info, 'code_module', 'final_result', 'id_student', plot_size=(15, 8))

student_info['Code_Category'] = ['Social_Science' if student_info['code_module'].iloc[i] in ['AAA', 'BBB', 'GGG']
                                 else 'STEM' for i in range(len(student_info))]

## From the following plot we can see that Failure Rate is higher in Social Science and Withdrawn rate is higher in STEM Courses.

#stacked_plot(student_info, 'Code_Category', 'final_result', 'id_student', plot_size=(15, 8))

"""# Baseline Data & Implementation

## Data Preparation
"""

# In this step, I will remove code_module, code_presentation, id_student and Year as those won't have impact on the result
student_info2 = student_info.copy()

student_info = student_info.drop(['code_presentation', 'id_student', 'Year'], axis = 1)

student_info['date_registration'] = student_info['date_registration'].astype(float)

student_info['date_registration'].describe()

# There are two types of categorical variables in the data.
# 1. NOMINAL :- Here there is no order in the categories
# 2. ORDINAL :- When there is order in the category

nominal_columns = ['gender', 'region', 'disability', 'Starting_Month', 'code_module', 'Code_Category']
ordinal_columns = ['highest_education', 'imd_band', 'age_band']

# Function to Encode the Categorical Data Columns
# Parameters 1. df :- Dataframe 2. Column_name :- Feature to encode

def categorical_encoding(df, column_name_list=[]):

    for column_name in column_name_list:
        print(df[column_name].unique())
        categorical_columns = pd.get_dummies(df[column_name], prefix = column_name,
                                             prefix_sep = '_', drop_first = False)
        df = pd.concat([df, categorical_columns], axis = 1)
        df = df.drop(column_name, axis = 1)
    return df


# Function to Label Encode the data
# Parameters :- 1. data :- Dataframe 2. columns_list :- List of columns to label encode

def labelEncoder(data, columns_list):
    for col in columns_list:
        encoder = LabelEncoder()
        data[col]  = encoder.fit_transform(data[col])
    return data

data = labelEncoder(student_info, ordinal_columns)
data = categorical_encoding(student_info, nominal_columns)

sns.countplot(x ='final_result', data = data)

plt.show()

## To built a simplified binary class model, I am labeling Distinction and Pass as 0 and Withdrawn and Failure as 1

data['Result']  = [0 if result in ['Pass', 'Distinction'] else 1 for result in data['final_result']]

## In this steP, I am creating a dropout column where we consider withdrawn as the dropout and everything else as no dropout
## '0' : Not Withdrawn, '1': 'Withdrawn'

data['dropout'] = [0 if result in ['Pass', 'Distinction', 'Fail'] else 1 for result in data['final_result']]

## Creating Feature and Target Dataframes

feature = data.drop(['final_result', 'Result'], axis = 1)
target  = data['Result']

## We can see that both the classes are close in numbers. So I will treat this as a balanced case of binary classification.

target.value_counts()

### Here we will split our data into training and testing. As we have less data, I will keep 80% of the data for
### training and only 20% for testing. I would like to have more data where I can create three separate datasets
### for training, validation and testing. As our objective here is to find features which impact the decision whether
### student will fail or not, I will use most for training only.

X_train, X_test, Y_train, Y_test = train_test_split(feature, target,
                                                    test_size = 0.2,
                                                    random_state = 123,
                                                    stratify=data.final_result)

# In this step I will create a feature and target set for the dropout vs non-dropout case

feature_dropout = data.drop(['final_result', 'dropout', 'Result'], axis = 1)
target_dropout  = data['dropout']

target_dropout.value_counts()

## Splitting Data into training and test sets

X_train_dropout, X_test_dropout, Y_train_dropout, Y_test_dropout = train_test_split(feature_dropout, target_dropout,
                                                                                    test_size = 0.2,
                                                                                    random_state = 123,
                                                                                    stratify=target_dropout)

"""## Random Forest Classifiers"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create and train Random Forest model
rf = RandomForestClassifier(
    n_estimators=300,     # number of trees
    max_depth=25,      # can tune
    random_state=123,
)

rf.fit(X_train, Y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluate
accuracy = accuracy_score(Y_test, y_pred)
print(f"Random Forest Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(Y_test, y_pred))

importances = rf.feature_importances_
indices = np.argsort(importances)[::-1]
feature_names = X_train.columns

plt.figure(figsize=(10, 8))
plt.title("Random Forest Feature Importances")
plt.bar(range(20), importances[indices[:20]], align='center')
plt.xticks(range(20), feature_names[indices[:20]], rotation=90)
plt.tight_layout()
plt.show()

"""### Old RFC"""

## Initializing the Random Forest Model

random_forest_model = RandomForestClassifier(n_estimators=100,
                                             random_state=123,
                                             max_depth=25,
                                             min_samples_split = 100,
                                             n_jobs=4)

## Fitting the model using Training Data

random_forest_model.fit(X_train, Y_train)

## Predicting on Test Data using fitted model

predictions_random = random_forest_model.predict(X_test)

print(confusion_matrix(Y_test, predictions_random))

print("Accuracy of the model is ", accuracy_score(Y_test, predictions_random))

print(classification_report(Y_test, predictions_random, digits=2))

predictions_rf = random_forest_model.predict_proba(X_test)
preds = predictions_rf[:,1]
y_test = np.array(Y_test)
fpr, tpr, threshold = metrics.roc_curve(y_test, preds)
roc_auc = metrics.auc(fpr, tpr)


plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

# Grid Search
random_forest_model_best_fit = RandomForestClassifier(n_estimators=100,
                                                      random_state=123,
                                                   max_depth=30,
                                                      min_samples_split = 50,
                                                      n_jobs=4)

random_forest_model_best_fit.fit(X_train, Y_train)

predict_best_fit = random_forest_model_best_fit.predict(X_test)

print(classification_report(predict_best_fit, Y_test))

## We can see that region has close to None impact on the output of the model. So we will remove this feature.

importance = pd.concat([pd.DataFrame(X_train.columns),
                          pd.DataFrame(np.transpose(random_forest_model.feature_importances_))], axis = 1)
importance.columns = ['Features', 'Coeff']
importance = importance.sort_values('Coeff', ascending=False)
importance

#Building amodel to predict whether student will dropout or not
# I am using class weight in this case because we have less samples for class = 1 which is dropout

random_forest_model_drop = RandomForestClassifier(n_estimators=100,
                                                  random_state=123,
                                                  max_depth=25,
                                                  min_samples_split = 100,
                                                  class_weight = {0: 1, 1: 2},
                                                  n_jobs=4)

random_forest_model_drop.fit(X_train_dropout, Y_train_dropout)

predict_dropout = random_forest_model_drop.predict(X_test_dropout)

print(classification_report(predict_dropout, Y_test_dropout))

predictions_rf = random_forest_model_drop.predict_proba(X_test_dropout)
preds = predictions_rf[:,1]
y_test = np.array(Y_test_dropout)
fpr, tpr, threshold = metrics.roc_curve(y_test, preds)
roc_auc = metrics.auc(fpr, tpr)


plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

importance = pd.concat([pd.DataFrame(X_train_dropout.columns),
                          pd.DataFrame(np.transpose(random_forest_model_drop.feature_importances_))], axis = 1)
importance.columns = ['Features', 'Coeff']
importance = importance.sort_values('Coeff', ascending=False)
importance

"""## XGBoost"""

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

dtrain = xgb.DMatrix(X_train, label=Y_train)
dtest = xgb.DMatrix(X_test, label=Y_test)

params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 5,
    'eta' : 0.1,
    'subsample' : 0.8,
    'colsample_bytree': 0.8,
    'random_state': 123
}

xgb_model = xgb.train(params, dtrain, num_boost_round=200, evals=[(dtest, 'test')], early_stopping_rounds=20, verbose_eval=False)

y_pred_prob = xgb_model.predict(dtest)
y_pred = (y_pred_prob > 0.5).astype(int)

print("Accuracy:", accuracy_score(Y_test, y_pred))
print("ROC AUC:", roc_auc_score(Y_test, y_pred_prob))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))


#feature importance
xgb.plot_importance(xgb_model, max_num_features=10)
plt.show()

"""## Decision Tree"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Create and train the model
dt = DecisionTreeClassifier(
    criterion='gini',       # or 'entropy'
    max_depth=4,         # can tune later
    random_state=123
)

dt.fit(X_train, Y_train)

# Predictions
y_pred = dt.predict(X_test)

# Plot the decision tree
plt.figure(figsize=(12, 8))
plot_tree(dt, feature_names=X_test.columns, filled=True)
plt.show()

# Evaluate
accuracy = accuracy_score(Y_test, y_pred)
print(f"Decision Tree Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(Y_test, y_pred))

feature_importance = pd.Series(dt.feature_importances_, index=X_train.columns)

# Sort by importance
feature_importance = feature_importance.sort_values(ascending=False)

# Optional: plot feature importance
plt.figure(figsize=(10,6))
feature_importance.head(15).plot(kind='bar')
plt.title("Decision Tree Feature Importance")
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

"""# Augmented Data & Implementation

## Creating Aumented Data
"""



#finding which columns are in both student_info and student_assement
common_cols = set(student_info2.columns).intersection(student_assessment_merge_assessment.columns)
print(common_cols)

#don't want to drop student id because this is how we will merge
common_cols.remove('id_student')

#dropping common columns
assessments_clean = student_assessment_merge_assessment.drop(columns=common_cols)

#merging student info with assessments
student_info2 = pd.merge(student_info2, assessments_clean, on="id_student", how="left")

student_info2.head()

# In this step, I will remove code_presentation, id_student and Year as those won't have impact on the result

student_info2 = student_info2.drop(['code_presentation', 'id_student', 'Year'], axis = 1)

student_info2['date_registration'] = student_info2['date_registration'].astype(float)

student_info2['date_registration'].describe()

"""## Building the Model"""

# Putting all the merging and dataset code here so we do not have to run everything whenever we reopen the document
student_info2.isnull().sum()

student_info2 = student_info2.dropna()

student_info2.head()

"""## Splitting Data"""

student_info2 = student_info2.drop(['id_assessment', 'After_Clicks', 'Before_Clicks', 'date'], axis = 1)

test = student_info2
test['Result']  = [0 if result in ['Pass', 'Distinction'] else 1 for result in test['final_result']]
test

feature = test.drop(['final_result', 'Result'], axis = 1)
target  = test['Result']

target.value_counts()

#encode before splitting

feature = pd.get_dummies(feature, drop_first=True)

#FIRST SPLITTING INTO TRAIN AND TEMP

X_train, X_temp, Y_train, Y_temp = train_test_split(
    feature, target,
    test_size=0.3,
    random_state=123,
    stratify=target
)

# SPLITTING TEMP INTO TEST AND VALIDATION
X_test, X_val, Y_test, Y_val = train_test_split(
    X_temp, Y_temp,
    test_size=1/3,
    random_state=123,
    stratify=Y_temp
)

#COMBINING X AND Y TO DOWNLOAD
train = pd.concat([X_train, Y_train], axis=1)
test = pd.concat([X_test, Y_test], axis=1)
val = pd.concat([X_val, Y_val], axis=1)

#SAVE AS CSV
train.to_csv('train.csv', index=False)
test.to_csv('test.csv', index=False)
val.to_csv('val.csv', index=False)

train

"""### Multicollinearity"""

# Check Multicollinearity (VIF)

'''
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd
import statsmodels.api as sm

# Assume X_train_encoded is already one-hot encoded and float
# Add constant for intercept (needed for statsmodels)
X_train_const = sm.add_constant(X_train)

# Create DataFrame to hold VIF values
vif_data = pd.DataFrame()
vif_data['Feature'] = X_train_const.columns

# Calculate VIF for each feature
vif_data['VIF'] = [
    variance_inflation_factor(X_train_const.values, i)
    for i in range(X_train_const.shape[1])
]

print(vif_data.sort_values('VIF', ascending=False))

'''

"""Here we have high VIF. We want to drpop any below 10, but code_module and region should be okayish to keep."""

'''
#REMOVE HIGH VIF AND TEST AGAIN

#X_train_encoded = X_train_encoded.drop("sum_click", axis = 1)

X_train_const = sm.add_constant(X_train)

# Create DataFrame to hold VIF values
vif_data = pd.DataFrame()
vif_data['Feature'] = X_train_const.columns

# Calculate VIF for each feature
vif_data['VIF'] = [
    variance_inflation_factor(X_train_const.values, i)
    for i in range(X_train_const.shape[1])
]

print(vif_data.sort_values('VIF', ascending=False))
'''

'''
# Check if sum_click is derived from others
test['check'] = test['Before_Clicks'] + test['After_Clicks']
test['check'].equals(test['sum_click'])  # if True, drop sum_click or components
'''

"""## XGBoost"""

# One-hot encode categorical variables
#X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Force all values to float (prevents "object" dtype)
#X_test_encoded = X_test_encoded.astype(float)

clean = lambda c: c.replace('[', '(').replace(']', ')').replace('<', 'LT_')

X_train.columns = [clean(c) for c in X_train.columns]
X_test.columns  = [clean(c) for c in X_test.columns]

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

dtrain = xgb.DMatrix(X_train, label=Y_train)
dtest = xgb.DMatrix(X_test, label=Y_test)

params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 5,
    'eta' : 0.1,
    'subsample' : 0.8,
    'colsample_bytree': 0.8,
    'random_state': 123
}

xgb_model = xgb.train(params, dtrain, num_boost_round=200, evals=[(dtest, 'test')], early_stopping_rounds=20, verbose_eval=False)

y_pred_prob = xgb_model.predict(dtest)
y_pred = (y_pred_prob > 0.5).astype(int)

print("Accuracy:", accuracy_score(Y_test, y_pred))
print("ROC AUC:", roc_auc_score(Y_test, y_pred_prob))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))


#feature importance
xgb.plot_importance(xgb_model, max_num_features=10)
plt.show()

"""## Random Forest"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create and train Random Forest model
rf = RandomForestClassifier(
    n_estimators=300,     # number of trees
    max_depth=25,      # can tune
    random_state=123,
)

rf.fit(X_train, Y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluate
accuracy = accuracy_score(Y_test, y_pred)
print(f"Random Forest Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(Y_test, y_pred))

importances = rf.feature_importances_
indices = np.argsort(importances)[::-1]
feature_names = X_train.columns

plt.figure(figsize=(10, 8))
plt.title("Random Forest Feature Importances")
plt.bar(range(20), importances[indices[:20]], align='center')
plt.xticks(range(20), feature_names[indices[:20]], rotation=90)
plt.tight_layout()
plt.show()

"""## Decision Tree"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Create and train the model
dt = DecisionTreeClassifier(
    criterion='gini',       # or 'entropy'
    max_depth=4,         # can tune later
    random_state=123
)

dt.fit(X_train, Y_train)

# Predictions
y_pred = dt.predict(X_test)

# Plot the decision tree
plt.figure(figsize=(12, 8))
plot_tree(dt, feature_names=X_test.columns, filled=True)
plt.show()

# Evaluate
accuracy = accuracy_score(Y_test, y_pred)
print(f"Decision Tree Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(Y_test, y_pred))


feature_importance = pd.Series(dt.feature_importances_, index=X_train.columns)

# Sort by importance
feature_importance = feature_importance.sort_values(ascending=False)

# Optional: plot feature importance
plt.figure(figsize=(10,6))
feature_importance.head(15).plot(kind='bar')
plt.title("Decision Tree Feature Importance")
plt.ylabel("Importance")
plt.tight_layout()
plt.show()